// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlemaps.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the GoogleMaps module

	public static boolean bCo_Location(IContext context, googlemaps.proxies.Location _location)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Location", _location == null ? null : _location.getMendixObject());
			return (Boolean)Core.execute(context, "GoogleMaps.BCo_Location", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}