// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oauthmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the OauthModule module

	public static String getCallbackURI_Facebook()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.CallbackURI_Facebook");
	}

	public static String getCallbackURI_Google()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.CallbackURI_Google");
	}

	public static String getCallbackURI_Linkedin()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.CallbackURI_Linkedin");
	}

	public static String getCallbackURI_Uber()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.CallbackURI_Uber");
	}

	public static boolean getCleanupOAuthLogAccessStateError()
	{
		return (Boolean)Core.getConfiguration().getConstantValue("OauthModule.CleanupOAuthLogAccessStateError");
	}

	public static boolean getCleanupOAuthLogXSSUnauthorized()
	{
		return (Boolean)Core.getConfiguration().getConstantValue("OauthModule.CleanupOAuthLogXSSUnauthorized");
	}

	public static String getClientId_Facebook()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientId_Facebook");
	}

	public static String getClientId_Google()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientId_Google");
	}

	public static String getClientId_Linkedin()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientId_Linkedin");
	}

	public static String getClientId_Uber()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientId_Uber");
	}

	public static String getClientSecret_Facebook()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientSecret_Facebook");
	}

	public static String getClientSecret_Google()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientSecret_Google");
	}

	public static String getClientSecret_Linkedin()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientSecret_Linkedin");
	}

	public static String getClientSecret_Uber()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.ClientSecret_Uber");
	}

	public static String getCookieErrorPage()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.CookieErrorPage");
	}

	public static String getCookieName()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.CookieName");
	}

	public static String getIndexPage()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.IndexPage");
	}

	public static String getOAuthTokenURI_Facebook()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthTokenURI_Facebook");
	}

	public static String getOAuthTokenURI_Google()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthTokenURI_Google");
	}

	public static String getOAuthTokenURI_Linkedin()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthTokenURI_Linkedin");
	}

	public static String getOAuthTokenURI_Uber()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthTokenURI_Uber");
	}

	public static String getOAuthURI_Facebook()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthURI_Facebook");
	}

	public static String getOAuthURI_Google()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthURI_Google");
	}

	public static String getOAuthURI_Linkedin()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthURI_Linkedin");
	}

	public static String getOAuthURI_Uber()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.OAuthURI_Uber");
	}

	public static String getStateErrorPage()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.StateErrorPage");
	}

	public static String getUnauthorizedAccessPage()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.UnauthorizedAccessPage");
	}

	public static String getUserInfoURI_Facebook()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.UserInfoURI_Facebook");
	}

	public static String getUserInfoURI_Google()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.UserInfoURI_Google");
	}

	public static String getUserInfoURI_Linkedin()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.UserInfoURI_Linkedin");
	}

	public static String getUserInfoURI_Uber()
	{
		return (String)Core.getConfiguration().getConstantValue("OauthModule.UserInfoURI_Uber");
	}
}