// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies;

/**
 * 
 */
public class DriverObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject driverObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UberIntegration.DriverObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		picture_url("picture_url"),
		name("name"),
		rating("rating"),
		phone_number("phone_number"),
		RoundedRating("RoundedRating"),
		driver("UberIntegration.driver");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DriverObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UberIntegration.DriverObj"));
	}

	protected DriverObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject driverObjMendixObject)
	{
		if (driverObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UberIntegration.DriverObj", driverObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UberIntegration.DriverObj");

		this.driverObjMendixObject = driverObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DriverObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static uberintegration.proxies.DriverObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return uberintegration.proxies.DriverObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static uberintegration.proxies.DriverObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new uberintegration.proxies.DriverObj(context, mendixObject);
	}

	public static uberintegration.proxies.DriverObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return uberintegration.proxies.DriverObj.initialize(context, mendixObject);
	}

	public static java.util.List<uberintegration.proxies.DriverObj> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<uberintegration.proxies.DriverObj> result = new java.util.ArrayList<uberintegration.proxies.DriverObj>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UberIntegration.DriverObj" + xpathConstraint))
			result.add(uberintegration.proxies.DriverObj.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of picture_url
	 */
	public final String getpicture_url()
	{
		return getpicture_url(getContext());
	}

	/**
	 * @param context
	 * @return value of picture_url
	 */
	public final String getpicture_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.picture_url.toString());
	}

	/**
	 * Set value of picture_url
	 * @param picture_url
	 */
	public final void setpicture_url(String picture_url)
	{
		setpicture_url(getContext(), picture_url);
	}

	/**
	 * Set value of picture_url
	 * @param context
	 * @param picture_url
	 */
	public final void setpicture_url(com.mendix.systemwideinterfaces.core.IContext context, String picture_url)
	{
		getMendixObject().setValue(context, MemberNames.picture_url.toString(), picture_url);
	}

	/**
	 * @return value of name
	 */
	public final String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of rating
	 */
	public final Double getrating()
	{
		return getrating(getContext());
	}

	/**
	 * @param context
	 * @return value of rating
	 */
	public final Double getrating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.rating.toString());
	}

	/**
	 * Set value of rating
	 * @param rating
	 */
	public final void setrating(Double rating)
	{
		setrating(getContext(), rating);
	}

	/**
	 * Set value of rating
	 * @param context
	 * @param rating
	 */
	public final void setrating(com.mendix.systemwideinterfaces.core.IContext context, Double rating)
	{
		getMendixObject().setValue(context, MemberNames.rating.toString(), rating);
	}

	/**
	 * @return value of phone_number
	 */
	public final String getphone_number()
	{
		return getphone_number(getContext());
	}

	/**
	 * @param context
	 * @return value of phone_number
	 */
	public final String getphone_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.phone_number.toString());
	}

	/**
	 * Set value of phone_number
	 * @param phone_number
	 */
	public final void setphone_number(String phone_number)
	{
		setphone_number(getContext(), phone_number);
	}

	/**
	 * Set value of phone_number
	 * @param context
	 * @param phone_number
	 */
	public final void setphone_number(com.mendix.systemwideinterfaces.core.IContext context, String phone_number)
	{
		getMendixObject().setValue(context, MemberNames.phone_number.toString(), phone_number);
	}

	/**
	 * @return value of RoundedRating
	 */
	public final Integer getRoundedRating()
	{
		return getRoundedRating(getContext());
	}

	/**
	 * @param context
	 * @return value of RoundedRating
	 */
	public final Integer getRoundedRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.RoundedRating.toString());
	}

	/**
	 * Set value of RoundedRating
	 * @param roundedrating
	 */
	public final void setRoundedRating(Integer roundedrating)
	{
		setRoundedRating(getContext(), roundedrating);
	}

	/**
	 * Set value of RoundedRating
	 * @param context
	 * @param roundedrating
	 */
	public final void setRoundedRating(com.mendix.systemwideinterfaces.core.IContext context, Integer roundedrating)
	{
		getMendixObject().setValue(context, MemberNames.RoundedRating.toString(), roundedrating);
	}

	/**
	 * @return value of driver
	 */
	public final uberintegration.proxies.RequestResponse getdriver() throws com.mendix.core.CoreException
	{
		return getdriver(getContext());
	}

	/**
	 * @param context
	 * @return value of driver
	 */
	public final uberintegration.proxies.RequestResponse getdriver(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		uberintegration.proxies.RequestResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.driver.toString());
		if (identifier != null)
			result = uberintegration.proxies.RequestResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of driver
	 * @param driver
	 */
	public final void setdriver(uberintegration.proxies.RequestResponse driver)
	{
		setdriver(getContext(), driver);
	}

	/**
	 * Set value of driver
	 * @param context
	 * @param driver
	 */
	public final void setdriver(com.mendix.systemwideinterfaces.core.IContext context, uberintegration.proxies.RequestResponse driver)
	{
		if (driver == null)
			getMendixObject().setValue(context, MemberNames.driver.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.driver.toString(), driver.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return driverObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final uberintegration.proxies.DriverObj that = (uberintegration.proxies.DriverObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UberIntegration.DriverObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
