// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies;

/**
 * 
 */
public class LocationObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UberIntegration.LocationObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		latitude("latitude"),
		longitude("longitude"),
		location("UberIntegration.location");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LocationObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UberIntegration.LocationObj"));
	}

	protected LocationObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationObjMendixObject)
	{
		if (locationObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UberIntegration.LocationObj", locationObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UberIntegration.LocationObj");

		this.locationObjMendixObject = locationObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LocationObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static uberintegration.proxies.LocationObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return uberintegration.proxies.LocationObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static uberintegration.proxies.LocationObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new uberintegration.proxies.LocationObj(context, mendixObject);
	}

	public static uberintegration.proxies.LocationObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return uberintegration.proxies.LocationObj.initialize(context, mendixObject);
	}

	public static java.util.List<uberintegration.proxies.LocationObj> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<uberintegration.proxies.LocationObj> result = new java.util.ArrayList<uberintegration.proxies.LocationObj>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UberIntegration.LocationObj" + xpathConstraint))
			result.add(uberintegration.proxies.LocationObj.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of latitude
	 */
	public final Double getlatitude()
	{
		return getlatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of latitude
	 */
	public final Double getlatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.latitude.toString());
	}

	/**
	 * Set value of latitude
	 * @param latitude
	 */
	public final void setlatitude(Double latitude)
	{
		setlatitude(getContext(), latitude);
	}

	/**
	 * Set value of latitude
	 * @param context
	 * @param latitude
	 */
	public final void setlatitude(com.mendix.systemwideinterfaces.core.IContext context, Double latitude)
	{
		getMendixObject().setValue(context, MemberNames.latitude.toString(), latitude);
	}

	/**
	 * @return value of longitude
	 */
	public final Double getlongitude()
	{
		return getlongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of longitude
	 */
	public final Double getlongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.longitude.toString());
	}

	/**
	 * Set value of longitude
	 * @param longitude
	 */
	public final void setlongitude(Double longitude)
	{
		setlongitude(getContext(), longitude);
	}

	/**
	 * Set value of longitude
	 * @param context
	 * @param longitude
	 */
	public final void setlongitude(com.mendix.systemwideinterfaces.core.IContext context, Double longitude)
	{
		getMendixObject().setValue(context, MemberNames.longitude.toString(), longitude);
	}

	/**
	 * @return value of location
	 */
	public final uberintegration.proxies.RequestResponse getlocation() throws com.mendix.core.CoreException
	{
		return getlocation(getContext());
	}

	/**
	 * @param context
	 * @return value of location
	 */
	public final uberintegration.proxies.RequestResponse getlocation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		uberintegration.proxies.RequestResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.location.toString());
		if (identifier != null)
			result = uberintegration.proxies.RequestResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of location
	 * @param location
	 */
	public final void setlocation(uberintegration.proxies.RequestResponse location)
	{
		setlocation(getContext(), location);
	}

	/**
	 * Set value of location
	 * @param context
	 * @param location
	 */
	public final void setlocation(com.mendix.systemwideinterfaces.core.IContext context, uberintegration.proxies.RequestResponse location)
	{
		if (location == null)
			getMendixObject().setValue(context, MemberNames.location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.location.toString(), location.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final uberintegration.proxies.LocationObj that = (uberintegration.proxies.LocationObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UberIntegration.LocationObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
