// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies;

/**
 * 
 */
public class PriceObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject priceObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UberIntegration.PriceObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		product_id("product_id"),
		currency_code("currency_code"),
		display_name("display_name"),
		estimate("estimate"),
		low_estimate("low_estimate"),
		high_estimate("high_estimate"),
		surge_multiplier("surge_multiplier"),
		duration("duration"),
		distance("distance");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PriceObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UberIntegration.PriceObj"));
	}

	protected PriceObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject priceObjMendixObject)
	{
		if (priceObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UberIntegration.PriceObj", priceObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UberIntegration.PriceObj");

		this.priceObjMendixObject = priceObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PriceObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static uberintegration.proxies.PriceObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return uberintegration.proxies.PriceObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static uberintegration.proxies.PriceObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new uberintegration.proxies.PriceObj(context, mendixObject);
	}

	public static uberintegration.proxies.PriceObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return uberintegration.proxies.PriceObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of product_id
	 */
	public final String getproduct_id()
	{
		return getproduct_id(getContext());
	}

	/**
	 * @param context
	 * @return value of product_id
	 */
	public final String getproduct_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.product_id.toString());
	}

	/**
	 * Set value of product_id
	 * @param product_id
	 */
	public final void setproduct_id(String product_id)
	{
		setproduct_id(getContext(), product_id);
	}

	/**
	 * Set value of product_id
	 * @param context
	 * @param product_id
	 */
	public final void setproduct_id(com.mendix.systemwideinterfaces.core.IContext context, String product_id)
	{
		getMendixObject().setValue(context, MemberNames.product_id.toString(), product_id);
	}

	/**
	 * @return value of currency_code
	 */
	public final String getcurrency_code()
	{
		return getcurrency_code(getContext());
	}

	/**
	 * @param context
	 * @return value of currency_code
	 */
	public final String getcurrency_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.currency_code.toString());
	}

	/**
	 * Set value of currency_code
	 * @param currency_code
	 */
	public final void setcurrency_code(String currency_code)
	{
		setcurrency_code(getContext(), currency_code);
	}

	/**
	 * Set value of currency_code
	 * @param context
	 * @param currency_code
	 */
	public final void setcurrency_code(com.mendix.systemwideinterfaces.core.IContext context, String currency_code)
	{
		getMendixObject().setValue(context, MemberNames.currency_code.toString(), currency_code);
	}

	/**
	 * @return value of display_name
	 */
	public final String getdisplay_name()
	{
		return getdisplay_name(getContext());
	}

	/**
	 * @param context
	 * @return value of display_name
	 */
	public final String getdisplay_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.display_name.toString());
	}

	/**
	 * Set value of display_name
	 * @param display_name
	 */
	public final void setdisplay_name(String display_name)
	{
		setdisplay_name(getContext(), display_name);
	}

	/**
	 * Set value of display_name
	 * @param context
	 * @param display_name
	 */
	public final void setdisplay_name(com.mendix.systemwideinterfaces.core.IContext context, String display_name)
	{
		getMendixObject().setValue(context, MemberNames.display_name.toString(), display_name);
	}

	/**
	 * @return value of estimate
	 */
	public final String getestimate()
	{
		return getestimate(getContext());
	}

	/**
	 * @param context
	 * @return value of estimate
	 */
	public final String getestimate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.estimate.toString());
	}

	/**
	 * Set value of estimate
	 * @param estimate
	 */
	public final void setestimate(String estimate)
	{
		setestimate(getContext(), estimate);
	}

	/**
	 * Set value of estimate
	 * @param context
	 * @param estimate
	 */
	public final void setestimate(com.mendix.systemwideinterfaces.core.IContext context, String estimate)
	{
		getMendixObject().setValue(context, MemberNames.estimate.toString(), estimate);
	}

	/**
	 * @return value of low_estimate
	 */
	public final Double getlow_estimate()
	{
		return getlow_estimate(getContext());
	}

	/**
	 * @param context
	 * @return value of low_estimate
	 */
	public final Double getlow_estimate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.low_estimate.toString());
	}

	/**
	 * Set value of low_estimate
	 * @param low_estimate
	 */
	public final void setlow_estimate(Double low_estimate)
	{
		setlow_estimate(getContext(), low_estimate);
	}

	/**
	 * Set value of low_estimate
	 * @param context
	 * @param low_estimate
	 */
	public final void setlow_estimate(com.mendix.systemwideinterfaces.core.IContext context, Double low_estimate)
	{
		getMendixObject().setValue(context, MemberNames.low_estimate.toString(), low_estimate);
	}

	/**
	 * @return value of high_estimate
	 */
	public final Double gethigh_estimate()
	{
		return gethigh_estimate(getContext());
	}

	/**
	 * @param context
	 * @return value of high_estimate
	 */
	public final Double gethigh_estimate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.high_estimate.toString());
	}

	/**
	 * Set value of high_estimate
	 * @param high_estimate
	 */
	public final void sethigh_estimate(Double high_estimate)
	{
		sethigh_estimate(getContext(), high_estimate);
	}

	/**
	 * Set value of high_estimate
	 * @param context
	 * @param high_estimate
	 */
	public final void sethigh_estimate(com.mendix.systemwideinterfaces.core.IContext context, Double high_estimate)
	{
		getMendixObject().setValue(context, MemberNames.high_estimate.toString(), high_estimate);
	}

	/**
	 * @return value of surge_multiplier
	 */
	public final Integer getsurge_multiplier()
	{
		return getsurge_multiplier(getContext());
	}

	/**
	 * @param context
	 * @return value of surge_multiplier
	 */
	public final Integer getsurge_multiplier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.surge_multiplier.toString());
	}

	/**
	 * Set value of surge_multiplier
	 * @param surge_multiplier
	 */
	public final void setsurge_multiplier(Integer surge_multiplier)
	{
		setsurge_multiplier(getContext(), surge_multiplier);
	}

	/**
	 * Set value of surge_multiplier
	 * @param context
	 * @param surge_multiplier
	 */
	public final void setsurge_multiplier(com.mendix.systemwideinterfaces.core.IContext context, Integer surge_multiplier)
	{
		getMendixObject().setValue(context, MemberNames.surge_multiplier.toString(), surge_multiplier);
	}

	/**
	 * @return value of duration
	 */
	public final Double getduration()
	{
		return getduration(getContext());
	}

	/**
	 * @param context
	 * @return value of duration
	 */
	public final Double getduration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.duration.toString());
	}

	/**
	 * Set value of duration
	 * @param duration
	 */
	public final void setduration(Double duration)
	{
		setduration(getContext(), duration);
	}

	/**
	 * Set value of duration
	 * @param context
	 * @param duration
	 */
	public final void setduration(com.mendix.systemwideinterfaces.core.IContext context, Double duration)
	{
		getMendixObject().setValue(context, MemberNames.duration.toString(), duration);
	}

	/**
	 * @return value of distance
	 */
	public final Double getdistance()
	{
		return getdistance(getContext());
	}

	/**
	 * @param context
	 * @return value of distance
	 */
	public final Double getdistance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.distance.toString());
	}

	/**
	 * Set value of distance
	 * @param distance
	 */
	public final void setdistance(Double distance)
	{
		setdistance(getContext(), distance);
	}

	/**
	 * Set value of distance
	 * @param context
	 * @param distance
	 */
	public final void setdistance(com.mendix.systemwideinterfaces.core.IContext context, Double distance)
	{
		getMendixObject().setValue(context, MemberNames.distance.toString(), distance);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return priceObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final uberintegration.proxies.PriceObj that = (uberintegration.proxies.PriceObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UberIntegration.PriceObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
