// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies;

/**
 * 
 */
public class Profile
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject profileMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UberIntegration.Profile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		first_name("first_name"),
		last_name("last_name"),
		email("email"),
		picture("picture"),
		promo_code("promo_code"),
		uuid("uuid");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Profile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UberIntegration.Profile"));
	}

	protected Profile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profileMendixObject)
	{
		if (profileMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UberIntegration.Profile", profileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UberIntegration.Profile");

		this.profileMendixObject = profileMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Profile.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static uberintegration.proxies.Profile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return uberintegration.proxies.Profile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static uberintegration.proxies.Profile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new uberintegration.proxies.Profile(context, mendixObject);
	}

	public static uberintegration.proxies.Profile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return uberintegration.proxies.Profile.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of first_name
	 */
	public final String getfirst_name()
	{
		return getfirst_name(getContext());
	}

	/**
	 * @param context
	 * @return value of first_name
	 */
	public final String getfirst_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.first_name.toString());
	}

	/**
	 * Set value of first_name
	 * @param first_name
	 */
	public final void setfirst_name(String first_name)
	{
		setfirst_name(getContext(), first_name);
	}

	/**
	 * Set value of first_name
	 * @param context
	 * @param first_name
	 */
	public final void setfirst_name(com.mendix.systemwideinterfaces.core.IContext context, String first_name)
	{
		getMendixObject().setValue(context, MemberNames.first_name.toString(), first_name);
	}

	/**
	 * @return value of last_name
	 */
	public final String getlast_name()
	{
		return getlast_name(getContext());
	}

	/**
	 * @param context
	 * @return value of last_name
	 */
	public final String getlast_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.last_name.toString());
	}

	/**
	 * Set value of last_name
	 * @param last_name
	 */
	public final void setlast_name(String last_name)
	{
		setlast_name(getContext(), last_name);
	}

	/**
	 * Set value of last_name
	 * @param context
	 * @param last_name
	 */
	public final void setlast_name(com.mendix.systemwideinterfaces.core.IContext context, String last_name)
	{
		getMendixObject().setValue(context, MemberNames.last_name.toString(), last_name);
	}

	/**
	 * @return value of email
	 */
	public final String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * @return value of picture
	 */
	public final String getpicture()
	{
		return getpicture(getContext());
	}

	/**
	 * @param context
	 * @return value of picture
	 */
	public final String getpicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.picture.toString());
	}

	/**
	 * Set value of picture
	 * @param picture
	 */
	public final void setpicture(String picture)
	{
		setpicture(getContext(), picture);
	}

	/**
	 * Set value of picture
	 * @param context
	 * @param picture
	 */
	public final void setpicture(com.mendix.systemwideinterfaces.core.IContext context, String picture)
	{
		getMendixObject().setValue(context, MemberNames.picture.toString(), picture);
	}

	/**
	 * @return value of promo_code
	 */
	public final String getpromo_code()
	{
		return getpromo_code(getContext());
	}

	/**
	 * @param context
	 * @return value of promo_code
	 */
	public final String getpromo_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.promo_code.toString());
	}

	/**
	 * Set value of promo_code
	 * @param promo_code
	 */
	public final void setpromo_code(String promo_code)
	{
		setpromo_code(getContext(), promo_code);
	}

	/**
	 * Set value of promo_code
	 * @param context
	 * @param promo_code
	 */
	public final void setpromo_code(com.mendix.systemwideinterfaces.core.IContext context, String promo_code)
	{
		getMendixObject().setValue(context, MemberNames.promo_code.toString(), promo_code);
	}

	/**
	 * @return value of uuid
	 */
	public final String getuuid()
	{
		return getuuid(getContext());
	}

	/**
	 * @param context
	 * @return value of uuid
	 */
	public final String getuuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.uuid.toString());
	}

	/**
	 * Set value of uuid
	 * @param uuid
	 */
	public final void setuuid(String uuid)
	{
		setuuid(getContext(), uuid);
	}

	/**
	 * Set value of uuid
	 * @param context
	 * @param uuid
	 */
	public final void setuuid(com.mendix.systemwideinterfaces.core.IContext context, String uuid)
	{
		getMendixObject().setValue(context, MemberNames.uuid.toString(), uuid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return profileMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final uberintegration.proxies.Profile that = (uberintegration.proxies.Profile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UberIntegration.Profile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
