// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies;

/**
 * 
 */
public class PromotionObj
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject promotionObjMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UberIntegration.PromotionObj";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		display_text("display_text"),
		localized_value("localized_value"),
		_type("_type");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PromotionObj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UberIntegration.PromotionObj"));
	}

	protected PromotionObj(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject promotionObjMendixObject)
	{
		if (promotionObjMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UberIntegration.PromotionObj", promotionObjMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UberIntegration.PromotionObj");

		this.promotionObjMendixObject = promotionObjMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PromotionObj.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static uberintegration.proxies.PromotionObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return uberintegration.proxies.PromotionObj.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static uberintegration.proxies.PromotionObj initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new uberintegration.proxies.PromotionObj(context, mendixObject);
	}

	public static uberintegration.proxies.PromotionObj load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return uberintegration.proxies.PromotionObj.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of display_text
	 */
	public final String getdisplay_text()
	{
		return getdisplay_text(getContext());
	}

	/**
	 * @param context
	 * @return value of display_text
	 */
	public final String getdisplay_text(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.display_text.toString());
	}

	/**
	 * Set value of display_text
	 * @param display_text
	 */
	public final void setdisplay_text(String display_text)
	{
		setdisplay_text(getContext(), display_text);
	}

	/**
	 * Set value of display_text
	 * @param context
	 * @param display_text
	 */
	public final void setdisplay_text(com.mendix.systemwideinterfaces.core.IContext context, String display_text)
	{
		getMendixObject().setValue(context, MemberNames.display_text.toString(), display_text);
	}

	/**
	 * @return value of localized_value
	 */
	public final String getlocalized_value()
	{
		return getlocalized_value(getContext());
	}

	/**
	 * @param context
	 * @return value of localized_value
	 */
	public final String getlocalized_value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.localized_value.toString());
	}

	/**
	 * Set value of localized_value
	 * @param localized_value
	 */
	public final void setlocalized_value(String localized_value)
	{
		setlocalized_value(getContext(), localized_value);
	}

	/**
	 * Set value of localized_value
	 * @param context
	 * @param localized_value
	 */
	public final void setlocalized_value(com.mendix.systemwideinterfaces.core.IContext context, String localized_value)
	{
		getMendixObject().setValue(context, MemberNames.localized_value.toString(), localized_value);
	}

	/**
	 * @return value of _type
	 */
	public final String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return promotionObjMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final uberintegration.proxies.PromotionObj that = (uberintegration.proxies.PromotionObj) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UberIntegration.PromotionObj";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
