// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies;

/**
 * 
 */
public class RequestResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UberIntegration.RequestResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		request_id("request_id"),
		status("status"),
		eta("eta"),
		surge_multiplier("surge_multiplier"),
		ShowUpdate("ShowUpdate"),
		vehicle("UberIntegration.vehicle"),
		driver("UberIntegration.driver"),
		location("UberIntegration.location");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UberIntegration.RequestResponse"));
	}

	protected RequestResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestResponseMendixObject)
	{
		if (requestResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UberIntegration.RequestResponse", requestResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UberIntegration.RequestResponse");

		this.requestResponseMendixObject = requestResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RequestResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static uberintegration.proxies.RequestResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return uberintegration.proxies.RequestResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static uberintegration.proxies.RequestResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new uberintegration.proxies.RequestResponse(context, mendixObject);
	}

	public static uberintegration.proxies.RequestResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return uberintegration.proxies.RequestResponse.initialize(context, mendixObject);
	}

	public static java.util.List<uberintegration.proxies.RequestResponse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<uberintegration.proxies.RequestResponse> result = new java.util.ArrayList<uberintegration.proxies.RequestResponse>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UberIntegration.RequestResponse" + xpathConstraint))
			result.add(uberintegration.proxies.RequestResponse.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of request_id
	 */
	public final String getrequest_id()
	{
		return getrequest_id(getContext());
	}

	/**
	 * @param context
	 * @return value of request_id
	 */
	public final String getrequest_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.request_id.toString());
	}

	/**
	 * Set value of request_id
	 * @param request_id
	 */
	public final void setrequest_id(String request_id)
	{
		setrequest_id(getContext(), request_id);
	}

	/**
	 * Set value of request_id
	 * @param context
	 * @param request_id
	 */
	public final void setrequest_id(com.mendix.systemwideinterfaces.core.IContext context, String request_id)
	{
		getMendixObject().setValue(context, MemberNames.request_id.toString(), request_id);
	}

	/**
	 * @return value of status
	 */
	public final String getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final String getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.status.toString());
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(String status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, String status)
	{
		getMendixObject().setValue(context, MemberNames.status.toString(), status);
	}

	/**
	 * @return value of eta
	 */
	public final Integer geteta()
	{
		return geteta(getContext());
	}

	/**
	 * @param context
	 * @return value of eta
	 */
	public final Integer geteta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.eta.toString());
	}

	/**
	 * Set value of eta
	 * @param eta
	 */
	public final void seteta(Integer eta)
	{
		seteta(getContext(), eta);
	}

	/**
	 * Set value of eta
	 * @param context
	 * @param eta
	 */
	public final void seteta(com.mendix.systemwideinterfaces.core.IContext context, Integer eta)
	{
		getMendixObject().setValue(context, MemberNames.eta.toString(), eta);
	}

	/**
	 * @return value of surge_multiplier
	 */
	public final Double getsurge_multiplier()
	{
		return getsurge_multiplier(getContext());
	}

	/**
	 * @param context
	 * @return value of surge_multiplier
	 */
	public final Double getsurge_multiplier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Double) getMendixObject().getValue(context, MemberNames.surge_multiplier.toString());
	}

	/**
	 * Set value of surge_multiplier
	 * @param surge_multiplier
	 */
	public final void setsurge_multiplier(Double surge_multiplier)
	{
		setsurge_multiplier(getContext(), surge_multiplier);
	}

	/**
	 * Set value of surge_multiplier
	 * @param context
	 * @param surge_multiplier
	 */
	public final void setsurge_multiplier(com.mendix.systemwideinterfaces.core.IContext context, Double surge_multiplier)
	{
		getMendixObject().setValue(context, MemberNames.surge_multiplier.toString(), surge_multiplier);
	}

	/**
	 * @return value of ShowUpdate
	 */
	public final Boolean getShowUpdate()
	{
		return getShowUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowUpdate
	 */
	public final Boolean getShowUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.ShowUpdate.toString());
	}

	/**
	 * Set value of ShowUpdate
	 * @param showupdate
	 */
	public final void setShowUpdate(Boolean showupdate)
	{
		setShowUpdate(getContext(), showupdate);
	}

	/**
	 * Set value of ShowUpdate
	 * @param context
	 * @param showupdate
	 */
	public final void setShowUpdate(com.mendix.systemwideinterfaces.core.IContext context, Boolean showupdate)
	{
		getMendixObject().setValue(context, MemberNames.ShowUpdate.toString(), showupdate);
	}

	/**
	 * @return value of vehicle
	 */
	public final uberintegration.proxies.VehicleObj getvehicle() throws com.mendix.core.CoreException
	{
		return getvehicle(getContext());
	}

	/**
	 * @param context
	 * @return value of vehicle
	 */
	public final uberintegration.proxies.VehicleObj getvehicle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		uberintegration.proxies.VehicleObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.vehicle.toString());
		if (identifier != null)
			result = uberintegration.proxies.VehicleObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of vehicle
	 * @param vehicle
	 */
	public final void setvehicle(uberintegration.proxies.VehicleObj vehicle)
	{
		setvehicle(getContext(), vehicle);
	}

	/**
	 * Set value of vehicle
	 * @param context
	 * @param vehicle
	 */
	public final void setvehicle(com.mendix.systemwideinterfaces.core.IContext context, uberintegration.proxies.VehicleObj vehicle)
	{
		if (vehicle == null)
			getMendixObject().setValue(context, MemberNames.vehicle.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.vehicle.toString(), vehicle.getMendixObject().getId());
	}

	/**
	 * @return value of driver
	 */
	public final uberintegration.proxies.DriverObj getdriver() throws com.mendix.core.CoreException
	{
		return getdriver(getContext());
	}

	/**
	 * @param context
	 * @return value of driver
	 */
	public final uberintegration.proxies.DriverObj getdriver(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		uberintegration.proxies.DriverObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.driver.toString());
		if (identifier != null)
			result = uberintegration.proxies.DriverObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of driver
	 * @param driver
	 */
	public final void setdriver(uberintegration.proxies.DriverObj driver)
	{
		setdriver(getContext(), driver);
	}

	/**
	 * Set value of driver
	 * @param context
	 * @param driver
	 */
	public final void setdriver(com.mendix.systemwideinterfaces.core.IContext context, uberintegration.proxies.DriverObj driver)
	{
		if (driver == null)
			getMendixObject().setValue(context, MemberNames.driver.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.driver.toString(), driver.getMendixObject().getId());
	}

	/**
	 * @return value of location
	 */
	public final uberintegration.proxies.LocationObj getlocation() throws com.mendix.core.CoreException
	{
		return getlocation(getContext());
	}

	/**
	 * @param context
	 * @return value of location
	 */
	public final uberintegration.proxies.LocationObj getlocation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		uberintegration.proxies.LocationObj result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.location.toString());
		if (identifier != null)
			result = uberintegration.proxies.LocationObj.load(context, identifier);
		return result;
	}

	/**
	 * Set value of location
	 * @param location
	 */
	public final void setlocation(uberintegration.proxies.LocationObj location)
	{
		setlocation(getContext(), location);
	}

	/**
	 * Set value of location
	 * @param context
	 * @param location
	 */
	public final void setlocation(com.mendix.systemwideinterfaces.core.IContext context, uberintegration.proxies.LocationObj location)
	{
		if (location == null)
			getMendixObject().setValue(context, MemberNames.location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.location.toString(), location.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final uberintegration.proxies.RequestResponse that = (uberintegration.proxies.RequestResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UberIntegration.RequestResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
