// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package uberintegration.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the UberIntegration module

	public static void aPI_DELETE_Request_ByID(IContext context, uberintegration.proxies.RequestResponse _requestResponse)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RequestResponse", _requestResponse == null ? null : _requestResponse.getMendixObject());
			Core.execute(context, "UberIntegration.API_DELETE_Request_ByID", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void aPI_GET_Authorize(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "UberIntegration.API_GET_Authorize", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.PricesObjReturn aPI_GET_Prices(IContext context, Double _startLongitude, Double _startLatitude, Double _finishLongitude, Double _finishLatitude)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("StartLongitude", _startLongitude);
			params.put("StartLatitude", _startLatitude);
			params.put("FinishLongitude", _finishLongitude);
			params.put("FinishLatitude", _finishLatitude);
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Prices", params);
			return result == null ? null : uberintegration.proxies.PricesObjReturn.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.ProductObj aPI_GET_Product_ByID(IContext context, String _productID)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ProductID", _productID);
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Product_ByID", params);
			return result == null ? null : uberintegration.proxies.ProductObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.ProductReturn aPI_GET_Products(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Products", params);
			return result == null ? null : uberintegration.proxies.ProductReturn.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.Profile aPI_GET_Profile(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Profile", params);
			return result == null ? null : uberintegration.proxies.Profile.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.RequestResponse aPI_GET_Request_ByID(IContext context, uberintegration.proxies.RequestResponse _requestResponse)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RequestResponse", _requestResponse == null ? null : _requestResponse.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Request_ByID", params);
			return result == null ? null : uberintegration.proxies.RequestResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.Map aPI_GET_Request_Map_ByID(IContext context, uberintegration.proxies.RequestResponse _requestResponse)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RequestResponse", _requestResponse == null ? null : _requestResponse.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Request_Map_ByID", params);
			return result == null ? null : uberintegration.proxies.Map.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.TimeReturnObj aPI_GET_Time(IContext context, Double _longitude, Double _latitude)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Longitude", _longitude);
			params.put("Latitude", _latitude);
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_GET_Time", params);
			return result == null ? null : uberintegration.proxies.TimeReturnObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.RequestResponse aPI_POST_Request(IContext context, uberintegration.proxies.Route _route)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Route", _route == null ? null : _route.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.API_POST_Request", params);
			return result == null ? null : uberintegration.proxies.RequestResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void aPI_PUT_UpdateStatus(IContext context, uberintegration.proxies.RequestResponse _requestResponse)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RequestResponse", _requestResponse == null ? null : _requestResponse.getMendixObject());
			Core.execute(context, "UberIntegration.API_PUT_UpdateStatus", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static Long cAL_Rating(IContext context, uberintegration.proxies.DriverObj _driverObj)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("DriverObj", _driverObj == null ? null : _driverObj.getMendixObject());
			return (Long)Core.execute(context, "UberIntegration.CAL_Rating", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.TimeReturnObj dSO_GetTimeEstimation(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.DSO_GetTimeEstimation", params);
			return result == null ? null : uberintegration.proxies.TimeReturnObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<uberintegration.proxies.PriceObj> gET_Prices(IContext context, uberintegration.proxies.Route _route)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Route", _route == null ? null : _route.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "UberIntegration.GET_Prices", params);
			java.util.List<uberintegration.proxies.PriceObj> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<uberintegration.proxies.PriceObj>();
				for (IMendixObject obj : objs)
					result.add(uberintegration.proxies.PriceObj.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.ProductObj gET_Product_ByPrice(IContext context, uberintegration.proxies.PriceObj _priceObj)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PriceObj", _priceObj == null ? null : _priceObj.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.GET_Product_ByPrice", params);
			return result == null ? null : uberintegration.proxies.ProductObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static uberintegration.proxies.ProductObj gET_Product_ByTime(IContext context, uberintegration.proxies.TimeObj _timeObj)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("TimeObj", _timeObj == null ? null : _timeObj.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "UberIntegration.GET_Product_ByTime", params);
			return result == null ? null : uberintegration.proxies.ProductObj.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_GetPricing(IContext context, uberintegration.proxies.Route _route)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Route", _route == null ? null : _route.getMendixObject());
			Core.execute(context, "UberIntegration.IVK_GetPricing", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_OpenAuthorize(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "UberIntegration.IVK_OpenAuthorize", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_OpenRoute(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "UberIntegration.IVK_OpenRoute", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_SelectPrice(IContext context, uberintegration.proxies.PriceObj _priceObj, uberintegration.proxies.Route _route)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PriceObj", _priceObj == null ? null : _priceObj.getMendixObject());
			params.put("Route", _route == null ? null : _route.getMendixObject());
			Core.execute(context, "UberIntegration.IVK_SelectPrice", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_UpdateRequest(IContext context, uberintegration.proxies.RequestResponse _requestResponse)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RequestResponse", _requestResponse == null ? null : _requestResponse.getMendixObject());
			Core.execute(context, "UberIntegration.IVK_UpdateRequest", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_UpdateStatus(IContext context, uberintegration.proxies.RequestResponse _requestResponse, uberintegration.proxies.Route _route)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("RequestResponse", _requestResponse == null ? null : _requestResponse.getMendixObject());
			params.put("Route", _route == null ? null : _route.getMendixObject());
			Core.execute(context, "UberIntegration.IVK_UpdateStatus", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}